### ISSUE TITLE
Object.hasBrand(obj, cls) alternative design

### ISSUE THREAD

**Issue by jorendorff** [ljharb/proposal-private-fields-in-in#3]
The purpose of this proposal is to support brand checks better. A possible alternative design is a standard library method, `Object.hasBrand(obj, cls)`, which returns **true** if *obj* has the private fields defined in *cls*. It can throw if *cls* doesn’t have any private fields, since in that case the spec says there is no brand to check.

The problem this solves is that the `#fieldname in obj` syntax is not quite in agreement with the rest of the language (see discussion in #2), so I vaguely expect we will regret it. It seems better if we can get the feature without new syntax.

But the private fields proposal deliberately doesn't offer any reification of private field names as values. To get around that, we use the constructor itself as a value representing a set of private names.

(A possible objection is that this allows code outside a class to brand-check objects. Is it a violation of privacy? I don’t think so; most object-oriented languages permit brand checks as long as the class itself is accessible.)

**Comment by ljharb** [comment]
Private fields aren’t the only brand - there’s also internal slots, so any general API method would need to also imo support those.

Separately, the class constructor doesn’t tell you what field to check since there’s both static fields and instance fields, so without reified private fields, this wouldn’t be possible.

Additionally yes, that is a violation; the only code that should be able to access a private field is code in the lexical scope of its class.

**Comment by jridgewell** [comment]
I think the bigger issue is that `Object.hasBrand` will be monkey-patchable, so it's not secure anymore.

- - -

A different possibility may be `#priv.has(obj)`, making it into a MetaProperty like `new.target`.

**Comment by ljharb** [comment]
No less secure than any static method, which first-run code always has to cache to ensure robustness.

`#priv.has(obj)` would work, but then it suggests that `#priv.has` should be a function somewhere, and also normal objects only have `.hasOwnProperty`, and it's a bad practice to directly call `.hasOwnProperty` anyways, so I'd prefer not to go in that direction.

**Comment by jorendorff** [comment]
> Private fields aren’t the only brand - there’s also internal slots, so any general API method would need to also imo support those.

I have two reactions to this:

1. That actually sounds kind of cool. Can we?

2. OK, but this argument cuts both ways. What you're saying is that if it's new syntax, it's OK for it to do something quite narrow, whereas if it has a name, then it needs to be _more_ generally applicable, or we can't do it at all. I thought the bar for new syntax was supposed to be _higher_ than for stdlib methods.

> Separately, the class constructor doesn’t tell you what field to check since there’s both static fields and instance fields, so without reified private fields, this wouldn’t be possible.

This seems unnecessary. Each static private field only exists on a single constructor object, right? Instead of brand-checking an object for a static field, can't you just test if it's `===` the constructor?

If this turns out to be something useful, it's possible to add something like `Object.hasStaticBrand(cls, cls)`.


> Additionally yes, that is a violation; the only code that should be able to access a private field is code in the lexical scope of its class.

Hmm. I don't understand how this is different from e.g. Java supporting `x instanceof String`, which does not actually provide access to the private `String` fields.

**Comment by ljharb** [comment]
> That actually sounds kind of cool. Can we?

I'd love to, see https://github.com/jasnell/proposal-istypes - but the implementation of that protocol would likely want to use this proposal's syntax :-)

> What you're saying is that if it's new syntax …

i'm not actually saying that; i'm saying that *private field syntax* already has a limited scope, and so using that syntax means that its semantics get to share that limited scope. Sticking something on `Object` does not enjoy those limits, and thus a broader scope is implied.
> Each static private field only exists on a single constructor object, right? 

No, every subclass of a constructor also has the same static private fields installed on it.

> Hmm. I don't understand how this is different from e.g. Java

JS private fields have (to my knowledge) the unique feature of true encapsulation, for which no reflection methods exist to break it; iow, JS here is different from (and imo better than) all other languages in terms of the concept of privacy.

**Comment by codehag** [comment]
> JS private fields have (to my knowledge) the unique feature of true encapsulation, for which no reflection methods exist to break it; iow, JS here is different from (and imo better than) all other languages in terms of the concept of privacy.

I think it is true that reflection doesn't exist for private fields, but I don't think that private fields have true encapsulation. At least, this is a point of contention.

**Comment by ljharb** [comment]
@codehag altho it'd be off topic for the thread, i'd love to hear more about that.

**Comment by jorendorff** [comment]
> No, every subclass of a constructor also has the same static private fields installed on it.

How does this work? I didn't look at the spec, I just tried it in Node 13.11.0:

```
> var q = 100;
undefined
> class B { static #x = q++; static x() { return this.#x; } }
undefined
> B.x()
100
> class D extends B { }
undefined
> D.x()
Uncaught:
TypeError: Cannot read private member #x from an object whose class did not declare it
    at Function.x (repl:1:53)
```

**Comment by jridgewell** [comment]
> > No, every subclass of a constructor also has the same static private fields installed on it.

> How does this work? I didn't look at the spec, I just tried it in Node 13.11.0:

This is the [static private footgun](https://github.com/tc39/proposal-class-fields/issues/43). The `D` class will not inherit the static private defined in `B`. Instead, `B.x` should be written as `static x() { return B.#x }` to avoid issues.

**Comment by ljharb** [comment]
You're right; I was remembering semantics from an earlier iteration of the proposal.

**Comment by littledan** [comment]
Right, we settled on semantics that just the one constructor has the private fields and methods; subclasses don't have them. The inheritance just happens on the instance side. We came to consensus as a committee that this was the best option.

**Comment by jorendorff** [comment]
OK, so to summarize the objections so far:

@ljharb:
> * [ ] Private fields aren’t the only brand - there’s also internal slots, so any general API method would need to also imo support those.
>
> * [x] Separately, the class constructor doesn’t tell you what field to check since there’s both static fields and instance fields, so without reified private fields, this wouldn’t be possible.
>
>     *(I think we're OK. Static private fields don't need to be tested, since there's already `===`.)*
>
> * [ ] Additionally yes, that is a violation; the only code that should be able to access a private field is code in the lexical scope of its class.

@jridgewell:
> * [x] I think the bigger issue is that Object.hasBrand will be monkey-patchable, so it's not secure anymore.
>
>     *(Many features, including potentially security-sensitive features, are exposed as methods, and there are standard techniques for dealing with monkeypatching.)*

If you think the ticked boxes are still not sufficiently answered, please speak up!

**Comment by jorendorff** [comment]
I want to try again to address the remaining objections.

> Private fields aren’t the only brand - there’s also internal slots, so any general API method would need to also imo support those.

Is this a consequence of the proposed method name `.hasBrand`? What if I instead chose `Object.hasPrivateFieldsOf(obj, cls)`?

> Additionally yes, that is a violation; the only code that should be able to access a private field is code in the lexical scope of its class.

Please help me understand this fully. The idea that encapsulation can include brand-checking is new to me. Why is that a good idea? What invariants do we get? Are there use cases that rely on brand-checking being impossible outside the class?

**Comment by ljharb** [comment]
That name certainly reduces the confusion, but at that point it breaks encapsulation - nobody outside the class should be able to detect the existence of private fields unless that ability has been explicitly exposed.

The main use case I have for private fields (something that's already stage 3, and whose existence is stipulated here) is being able to robustly identify an instance that my constructor created, in a way that can't be forged or removed, and that requires less boilerplate than a WeakMap-per-field in the class' closure.

The main use case I have for this proposal is to avoid needing a try/catch merely to try to do this identification. In other words, simple sugar for a common use case, that does not alter any characteristics of private fields (scope, observability, encapsulation, etc).

**Comment by jorendorff** [comment]
> That name certainly reduces the confusion, but at that point it breaks encapsulation[...]

OK, as I understand it, then, encapsulation is the primary issue.

> The main use case I have[...]

Thank you for caring about use cases! I should have mentioned that, in a departure from my usual attitude, I consider this proposal well-motivated already. :D This issue is about how to achieve the goal.

My questions remain: Why is it a good idea to treat brand-checking as a violation of encapsulation? What invariants (or other benefits) do we gain? (Or, put differently, what have systems like Java and C# lost by choosing the other route?) Are there use cases that rely on brand-checking being impossible outside the class?

Thanks again for your time.

**Comment by ljharb** [comment]
If the outside can brand check, then the addition of, or removal of, a private field becomes a breaking change. What java etc have lost is that they’ve become forced to define “breaking change” as “anything that breaks, except for when you use reflection”.

**Comment by jorendorff** [comment]
Oh, that's true. 

```js
class X {
    #x = 1;
}

// code outside the class
let obj = new X;
console.log(Object.hasPrivateFieldsOf(obj, X));  // true
```

Eliminating the private field, e.g. by moving it into a base class, or any of half a dozen other refactorings, would cause the `hasPrivateFieldsOf` call outside the class to break.

Java/C# can, for kind of unrelated reasons, conveniently do brand checks for any class, not just classes that have their own private fields. JS is different (under the private fields proposal).

**Comment by jorendorff** [comment]
This objection seems decisive to me, at the moment; someone can reopen if it looks like there's a way forward.

**Comment by bathos** [comment]
Although this is closed, I think it’s worth mentioning something here that I doesn’t otherwise seem to have appeared in the discussion.

```js
const Foo = new Proxy(class Foo { #bar; });
const foo = new Foo;

Object.hasPrivateFieldsOf(foo, Foo); // ???
```

Keeping in mind that `foo.#bar` does exist here, if the answer for `???` is `false`, we now have a way to detect if constructor objects are Proxy objects under certain circumstances where this shouldn’t be observable. But if it is `true`, I think we instead might have a channel that breaks membranes (not certain though ... struggling to picture it a bit tbh). I think there might be something fundamentally stinky abt trying to use the constructor as a key because it’s not the constructor object proper that has the private fields, it’s _what the constructor’s [[Construct]] actually happens to do,_ which could be a lot of things (think: constructor.bind(), return override, etc).

**Comment by ljharb** [comment]
@bathos private fields explicitly do not tunnel through proxies (just like internal slots of builtins), so that would have to *always* return false.

**Comment by bathos** [comment]
@ljharb The constructor is the proxy in this example, not the instance.

**Comment by ljharb** [comment]
Ah, I see what you mean - this seems identical to me as `class C {} ; Object.hasPrivateFieldsOf(new C(), C)` - iow, there's no private fields whatsoever, thus, should this return true or false? It's a tough question, since without any private fields, there's no possible authoritative `true`, and `false` might imply a lack of a link when one exists.

**Comment by bathos** [comment]
FWIW, I think this bolsters the case for the `#bar in foo`. Any generic public API solution means creating a new channel which exposes data about private fields to arbitrary observers. That’s iffy to begin with, but also causes the problem above. In a nutshell I think that’s because right now fields belong to “this code” (scoped by syntax) which is not quite the same thing as “this constructor” (because that code might be delegated to in any number of ways).
